# Generated by Django 5.0.2 on 2024-02-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lespays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pays', to='lespays.continent'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='superficie',
            field=models.FloatField(),
        ),
    ]
